# Generated by Django 2.2 on 2019-04-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0021_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=25)),
                ('Date', models.DateTimeField()),
                ('Temp', models.FloatField(max_length=6)),
            ],
        ),
    ]
